ALTER TABLE tasks
    ALTER COLUMN title SET NOT NULL,
    ALTER COLUMN description SET NOT NULL,
    ALTER COLUMN createdAt SET NOT NULL,
    ALTER COLUMN updatedAt SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN username SET NOT NULL;

ALTER TABLE types
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN description SET NOT NULL;

ALTER TABLE boards
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE columns
    ALTER COLUMN orderNumber SET NOT NULL,
    ALTER COLUMN board_id SET NOT NULL,
    ALTER COLUMN type_id SET NOT NULL;